export const COUNTRIES = [
  { value: "PL", label: "Polska" },
  { value: "DE", label: "Niemcy" },
  { value: "CZ", label: "Czechy" },
  { value: "SK", label: "Słowacja" },
  { value: "GB", label: "Wielka Brytania" },
  { value: "NL", label: "Holandia" },
  { value: "FR", label: "Francja" },
  { value: "IT", label: "Włochy" },
  { value: "ES", label: "Hiszpania" },
  { value: "AT", label: "Austria" },
  { value: "BE", label: "Belgia" },
  { value: "SE", label: "Szwecja" },
  { value: "NO", label: "Norwegia" },
  { value: "DK", label: "Dania" },
  { value: "FI", label: "Finlandia" },
  { value: "LT", label: "Litwa" },
  { value: "LV", label: "Łotwa" },
  { value: "EE", label: "Estonia" },
  { value: "RO", label: "Rumunia" },
  { value: "HU", label: "Węgry" },
  { value: "UA", label: "Ukraina" },
  { value: "CH", label: "Szwajcaria" },

  { value: "AF", label: "Afganistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algieria" },
  { value: "AD", label: "Andora" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua i Barbuda" },
  { value: "AR", label: "Argentyna" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AZ", label: "Azerbejdżan" },
  { value: "BS", label: "Bahamy" },
  { value: "BH", label: "Bahrajn" },
  { value: "BD", label: "Bangladesz" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Białoruś" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Boliwia" },
  { value: "BA", label: "Bośnia i Hercegowina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazylia" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bułgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Kambodża" },
  { value: "CM", label: "Kamerun" },
  { value: "CA", label: "Kanada" },
  { value: "CV", label: "Republika Zielonego Przylądka" },
  { value: "CF", label: "Republika Środkowoafrykańska" },
  { value: "TD", label: "Czad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "Chiny" },
  { value: "CO", label: "Kolumbia" },
  { value: "KM", label: "Komory" },
  { value: "CG", label: "Kongo" },
  { value: "CR", label: "Kostaryka" },
  { value: "HR", label: "Chorwacja" },
  { value: "CU", label: "Kuba" },
  { value: "CY", label: "Cypr" },
  { value: "DJ", label: "Dżibuti" },
  { value: "DM", label: "Dominika" },
  { value: "DO", label: "Dominikana" },
  { value: "EC", label: "Ekwador" },
  { value: "EG", label: "Egipt" },
  { value: "SV", label: "Salwador" },
  { value: "ET", label: "Etiopia" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Gruzja" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Grecja" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Gwatemala" },
  { value: "GN", label: "Gwinea" },
  { value: "GY", label: "Gujana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "IS", label: "Islandia" },
  { value: "IN", label: "Indie" },
  { value: "ID", label: "Indonezja" },
  { value: "IE", label: "Irlandia" },
  { value: "IL", label: "Izrael" },
  { value: "JP", label: "Japonia" },
  { value: "KE", label: "Kenia" },
  { value: "KR", label: "Korea Południowa" },
  { value: "LU", label: "Luksemburg" },
  { value: "MY", label: "Malezja" },
  { value: "MT", label: "Malta" },
  { value: "MX", label: "Meksyk" },
  { value: "PT", label: "Portugalia" },
  { value: "SI", label: "Słowenia" },
  { value: "TR", label: "Turcja" },
  { value: "US", label: "Stany Zjednoczone" },
  { value: "VN", label: "Wietnam" },
];
